# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  push:
    branches:    
      - 'deploy/**'
  # No automatic triggers
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-stage:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Build
        run: |
          npm install
          npx eslint --ext .ts .
  test-stage:
    runs-on: ubuntu-latest
    needs: build-stage
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          command that fails
  approve-stage:
    runs-on: ubuntu-latest
    needs: test-stage
    if: failure() || success()
    steps:
      - uses: actions/checkout@v3
      - name: Approve
        run: |
          npm install
  build-prod:
    runs-on: ubuntu-latest
    needs: approve-stage
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          npm install
          npx eslint --ext .ts .
