# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # No automatic triggers
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-stage:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build
        run: |
          npm install
          npx eslint --ext .ts .
  manual-approval:
    runs-on: ubuntu-latest
    needs: build-stage
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: user1,user2,org-team1
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''
  build-prod:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: manual-approval
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          npm install
          npx eslint --ext .ts .
