# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # No automatic triggers
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-stage:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Build
        run: |
          npm install
          npx eslint --ext .ts .
  test-stage:
    runs-on: ubuntu-latest
    needs: build-stage
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          poopy command that doesn't work
          echo "::warning test warning message"
  build-prod:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs:
      - build-stage
      - test-stage
    if: needs.build-stage.result == 'success' && needs.test-stage.result == 'failed'
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          npm install
          npx eslint --ext .ts .
